name: Auto Coverage Tracker
on:
  push:
    branches:
      - 'main'
jobs:
  calculate_coverage:
    if: github.repository == 'uva-bi-sdad/national_address_database'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "💡 The ${{ github.repository }} repository have been cloned to the runner."
      - run: echo "🌝 The repo is now cloned on the runner"
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository (Useful for debugging)
        run: |
          ls -la ${{ github.workspace }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6 #install the python needed
      - name: Install requirements
        run: |
          pip install -r requirements.txt 
      - name: Track coverage of counties per state, and overwrite to readme
        run: |
          python code/coverage.py -i data/fips_county.csv -d data/state_county -r README.md
      - name: Auto update listed county files in a json
        run: |
          tree -J data/state_county > data/state_county.json
      - name: Commit the results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automated coverage update"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
